version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: deploy_db_name
      MYSQL_USER: deploy_db_user
      MYSQL_PASSWORD: Myw8VVn8oOPzldO2dis6pyrAb

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost/:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./static/:.
      - ./media/:.

  web:
    container_name: models_project
    build: .
    restart: "always"
    environment:
      # - VIRTUAL_HOST=mysite.com
      - VIRTUAL_PORT=8000
      - TIMEOUT=300
      - HTTP_PORT=8000
      - STATS_PORT=8001
      - LANG=C.UTF-8
      - LANG en_US.UTF-8
      - LANGUAGE en_US:en
      - LC_ALL en_US.UTF-8
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - "db"

