version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: "always"
    ports:
      - "70:70"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: deploy_db_name
      MYSQL_USER: deploy_db_user
      MYSQL_PASSWORD: Myw8VVn8oOPzldO2dis6pyrAb

  web:
    container_name: "models_project"
    build: .
    restart: always
    volumes:
      - .:/code
    # environment:
      # - VIRTUAL_HOST=mysite.az
      # - VIRTUAL_PORT=7000
      # - TIMEOUT=300
      # - HTTP_PORT=7000
      # - STATS_PORT=8001
      # - LANG=C.UTF-8
      # - LANG en_US.UTF-8
      # - LANGUAGE en_US:en
      # - LC_ALL en_US.UTF-8
    ports:
      - 7000:8000
    depends_on:
      - db

