# Generated by Django 2.2.5 on 2019-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Adinizi daxil edin', max_length=50, verbose_name='Video bloggerin adi')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('avatar', models.ImageField(upload_to='blogger')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bloggerler',
                'ordering': ('-nickname',),
                'verbose_name': 'Blogger',
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, upload_to='video_images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='Videonun basligi buraya yazilmalidir...', max_length=20, verbose_name='Videonun basligi'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(blank=True, upload_to='video_files/'),
        ),
    ]
