# Generated by Django 2.2.5 on 2019-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0003_auto_20190916_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='gender',
            field=models.CharField(choices=[('k', 'Kisi'), ('q', 'Qadin')], default=1, max_length=1, verbose_name='Cinsi'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, verbose_name='Text field'),
        ),
    ]
