# Generated by Django 2.2.5 on 2019-09-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0005_auto_20190916_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Adı')),
                ('image', models.ImageField(upload_to='authors/')),
                ('gender', models.CharField(choices=[('k', 'Kisi'), ('q', 'Qadin')], max_length=1, verbose_name='Cinsi')),
                ('date_of_birthday', models.DateField()),
                ('nationality', models.CharField(max_length=30, verbose_name='Milliyeti')),
                ('info', models.TextField(verbose_name='Yazici haqqinda')),
            ],
            options={
                'verbose_name_plural': 'Yazicilar',
                'verbose_name': 'Yazici',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kitabin Başlığı')),
                ('description', models.TextField(verbose_name='Məzmun')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Qiymet')),
                ('page_count', models.IntegerField(verbose_name='Sehife sayi')),
                ('cover_image', models.ImageField(upload_to='books/', verbose_name='Cover sekili')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.Author')),
            ],
        ),
    ]
