# Generated by Django 2.2.5 on 2019-09-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0006_author_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='model_app.Category'),
        ),
    ]
