# Generated by Django 2.2.5 on 2019-09-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0008_auto_20190917_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('page_count',), 'verbose_name': 'Kitab', 'verbose_name_plural': 'Kitablar'},
        ),
    ]
