# Generated by Django 2.2.5 on 2019-10-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0011_auto_20190919_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='blogger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogger_videos', to='model_app.Blogger'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='model_app.Author', verbose_name='Muellif'),
        ),
    ]
